### ISSUE TITLE
V6.0 Release

### ISSUE THREAD

**Issue by mehranabi** [orchestral/kernel#15]
Hey,
Do you have any plan to release a version for latest changes (v6)?

**Comment by crynobone** [comment]
Not anytime soon to be honest.

**Comment by mehranabi** [comment]
Is there any way I can help to make it faster? 😄

**Comment by crynobone** [comment]
Do you need Kernel or just `orchestra/database`?

**Comment by mehranabi** [comment]
only `orchestra/database`

**Comment by crynobone** [comment]
Orchestra Testbench doesn't require `orchestra/database` since version 3.6, all the functionality is already available from Laravel Framework. If you still using it most probably it there doing nothing at the moment.

**Comment by mehranabi** [comment]
Oh I see, so I try to fix the code.
Thank you! 👍

**Comment by crynobone** [comment]
Let me know if you have any issue migration, but basically it just matter of removing from `composer.json` and the base `TestCase`.

See https://github.com/mtvs/eloquent-hashids/pull/14
