### ISSUE TITLE
Add Laravel v10 support

### ISSUE THREAD

**Issue by antonkomarev** [orchestral/kernel#17]
@crynobone Thank you for supporting this great tool!

Is there any plans to release Laravel v10 support anytime soon?
I have orchestra/database dependency and now it supports only Laravel v9

**Comment by crynobone** [comment]
`orchestra/database` is only required if you need to migrate using Testbench on Laravel 5+ AFAIK. You can safely remove it.

**Comment by antonkomarev** [comment]
Will try it, thanks

**Comment by antonkomarev** [comment]
Checked, it works without database dependency!
