### ISSUE TITLE
Config Publish Command

### ISSUE THREAD

**Issue by GrahamCampbell** [orchestral/kernel#3]
Is this going to be added?

**Comment by crynobone** [comment]
Available in https://github.com/orchestral/publisher

**Comment by GrahamCampbell** [comment]
Oh right. Thanks. I'm planning to use your config component in 20 of my laravel packages. :)

**Comment by crynobone** [comment]
Cool, to add on you could also consider looking at https://github.com/orchestral/support-providers and https://github.com/orchestral/database (migration support). 

The only thing missing (should be added) is migrate publish command which I feel need some tweak from the original code.

**Comment by GrahamCampbell** [comment]
Yeh, I've already checked out support-providers. Thanks. :)
